server:
  port: 80
  session:
    timeout: 1800
  tomcat: 
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
 
spring:
   datasource: 
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/catch_goods_db
     username: root
     password: liliu 
   redis:
     host: 127.0.0.1
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: null
  projectName: CatchGoods
  requestAuth: requestAuthDev
  sevenSecondsDomainUrl: http://192.168.11.111
  catchgoodsDomainUrl: http://192.168.11.111
  paymentSystemDomainUrl: http://192.168.11.111:8888
  rabbitmq:
    GOODSORDER_DIRECT_EXCHANGE: test.goodsorder.catchgoods.exchange.direct
    GOODSORDER_DIRECT_ROUTINGKEY: test.goodsorder.catchgoods.routingkey.direct
    GOODSORDER_DIRECT_QUEUE: test.goodsorder.catchgoods.queue.direct
    RECHARGERECORD_DIRECT_EXCHANGE: test.rechargerecord.catchgoods.exchange.direct
    RECHARGERECORD_DIRECT_ROUTINGKEY: test.rechargerecord.catchgoods.routingkey.direct
    RECHARGERECORD_DIRECT_QUEUE: test.rechargerecord.catchgoods.queue.direct
    CATCHRECORD_DIRECT_EXCHANGE: test.catchrecord.catchgoods.exchange.direct
    CATCHRECORD_DIRECT_ROUTINGKEY: test.catchrecord.catchgoods.routingkey.direct
    CATCHRECORD_DIRECT_QUEUE: test.catchrecord.catchgoods.queue.direct
    GOODSWEBREAD_DIRECT_EXCHANGE: test.goodswebread.catchgoods.exchange.direct
    GOODSWEBREAD_DIRECT_ROUTINGKEY: test.goodswebread.catchgoods.routingkey.direct
    GOODSWEBREAD_DIRECT_QUEUE: test.goodswebread.catchgoods.queue.direct
  aliyunSmsAppkey: LTAIgDJerZxD8twJ
  aliyunSmsAppsecret: 9PuLZNoEQRPDJm465MxL1JIXQY9Msh
  aliyunSmsSignName: 抓你妹
  aliyunSmsTemplateCodeAcountRegister: SMS_89885232
  aliyunSmsTemplateCodePasswordUpdate: SMS_89885231